ECOMM/ECOMM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

ECOMM/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns=[
    path('', HomeView.as_view(), name='home'),
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart')
]

ECOMM/home/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


CATEGORY = (
    ('S', 'Shirt'),
    ('SP', 'Sport Wear'),
    ('OW', 'Out Wear')
)

LABEL = (
    ('N', 'New'),
    ('BS', 'Best Seller')
)

class Item(models.Model) :
    item_name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY, max_length=2)
    label = models.CharField(choices=LABEL, max_length=2)
    description = models.TextField()

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            "pk" : self.pk
        
        })

    def get_add_to_cart_url(self) :
        return reverse("core:add-to-cart", kwargs={
            "pk" : self.pk
        })

    def get_remove_from_cart_url(self) :
        return reverse("core:remove-from-cart", kwargs={
            "pk" : self.pk
        })





class OrderItem(models.Model) :
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"


class Order(models.Model) :
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

ECOMM/home/views.py
from django.shortcuts import render
from django.contrib import messages                       
from django.shortcuts import render, get_object_or_404, redirect                      
from django.views.generic import ListView, DetailView                      
from django.utils import timezone                       
from .models import (                           
    Item,
    Order,
    OrderItem
)



class HomeView(ListView):
    model = Item
    template_name = "home/home.html"


class ProductView(DetailView):
    model = Item
    template_name = "home/product.html"


def add_to_cart(request, pk) :
    item = get_object_or_404(Item, pk = pk )
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user = request.user,
        ordered = False
    )
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    if order_qs.exists() :
        order = order_qs[0]
        
        if order.items.filter(item__pk = item.pk).exists() :
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added quantity Item")
            return redirect("home:product", pk = pk)
        else:
            order.items.add(order_item)
            messages.info(request, "Item added to your cart")
            return redirect("home:product", pk = pk)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date = ordered_date)
        order.items.add(order_item)
        messages.info(request, "Item added to your cart")
        return redirect("home:product", pk = pk)



def remove_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk )
    order_qs = Order.objects.filter(
        user=request.user, 
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order_item.delete()
            messages.info(request, "Item \""+order_item.item.item_name+"\" remove from your cart")
            return redirect("home:product")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("home:product", pk=pk)
    else:
        #add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("home:product", pk = pk)

ECOMM/templates/home/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <ul>
        {% for item in object_list %}
        <a href="{% url 'home:product' pk=item.pk %}">
            <li>{{ item.item_name }} - {{ item.price }}</li>
        </a>
        {% empty %}
        <p>No Item yet.</p>
        {% endfor %}
    </ul>

</body>

</html>

ECOMM/templates/home/product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .info{
            background-color: #319a4d;
            padding: 5px;
            border-radius: 3px;
            color: white;
        }
        .success{
            background-color: darkseagreen;
            padding: 5px;
            border-radius: 3px;
        }
        .warning{
            background-color: orange;
            padding: 5px;
            border-radius: 3px;
        }
        .error{
            background-color: orangered;
            color: white;
            padding: 5px;
            border-radius: 3px;
        }
    </style>
</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <section>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home:home' %}">Home</a>
                </li>
            </ul>
        </nav>
    </section>
    <strong><a href="{% url 'home:add-to-cart' pk=object.pk %}">Add to cart</a></strong>
    <h1>Item Name: {{ object.item_name }}</h1>
    <h2>Price: {{ object.price }}</h2>
    <h3>Discount Price: {{ object.discount_price }}</h3>
    <h4>Category: {{ object.category }}</h4>
    <h5>Label: {{ object.label }}</h5>
    <h6>Description: {{ object.description }}</h6>
</body>

</html>